### PR TITLE
RedissonSession#changeSessionId - PTTL and stale map fixes

### LINKED ISSUE #2692: RedissonSession#changeSessionId expiredKey race condition
We have a number of instances of our app in production, and we’ve encountered a race condition where the same session might have `changeSessionId` invoked on the same session separate servers. This means one server might receive [`-2` from `PTTL`](https://redis.io/commands/pttl), which isn’t currently handled.

<details>
<summary>Stacktrace</summary>
<pre>
org.redisson.client.RedisException: ERR invalid expire time in psetex. channel: [id: 0xf8f93a9c, L:/[redacted]:53574 - R:[redacted]:6379] command: (PSETEX), params: [spring:session:sessions:expires:[session id], -2, PooledUnsafeDirectByteBuf(ridx: 0, widx: 2, cap: 256)]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:355)
        at org.redisson.client.handler.CommandDecoder.decodeCommandBatch(CommandDecoder.java:266)
        at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:207)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:134)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1486)
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1235)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1282)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
</pre>
</details>

### PR DESCRIPTION
**Pull request by eager**
This fixes #2692 and #2693.

### CODE REVIEW

File: redisson/src/main/java/org/redisson/spring/session/RedissonSessionRepository.java [hunk 1]
```diff
@@ -214,14 +214,23 @@ public String changeSessionId() {
             Long remainTTL = (Long) list.get(0);
             Map<String, Object> oldState = (Map<String, Object>) list.get(2);
 
-            RBatch batchNew = redisson.createBatch(BatchOptions.defaults());
```
Comment (mrniko) [inline redisson/src/main/java/org/redisson/spring/session/RedissonSessionRepository.java:217]: Please use RBatch object

Comment (eager) [reply redisson/src/main/java/org/redisson/spring/session/RedissonSessionRepository.java:217]: @mrniko thanks, reverted to batch. While testing the fix, I thought we were getting exceptions when a batch only had a single command, but I seem to have been confused.

**Comment by mrniko** [comment]
Thanks for contribution!
