### PR TITLE
Fix #5426

### LINKED ISSUE #5426: request.changeSessionId does not change the session id in redis
This issue is similar to https://github.com/redisson/redisson/issues/1813, but affects redisson-tomcat.

**Expected behavior**

After changing the session id, attributes that were stored in the session should still be accessible.

**Actual behavior**

Session attributes are not copied or moved to the new session id.

**Steps to reproduce or test case**

any

**Redis version**

any

**Redisson version**

any

**Redisson configuration**

any

### PR DESCRIPTION
**Pull request by bclay2116**
Override changeSessionId from StandardSession to copy all items in old session to new in Redis layer.
This leaves intact all logic around when Session gets written to redis (Memory vs Redis and Default vs After Update) and ensures underlying cache is exactly the same as prior to ID change.

### CODE REVIEW

File: redisson-tomcat/redisson-tomcat-10/src/main/java/org/redisson/tomcat/RedissonSessionManager.java [hunk 1]
```diff
@@ -417,5 +417,15 @@ public void store(HttpSession session) throws IOException {
...
-    
+
+    @Override
+    protected void changeSessionId(Session session, String newId, boolean notifySessionListeners,
+            boolean notifyContainerListeners) {
+        String oldId = session.getIdInternal();
+        Map<String, Object> oldMap = getMap(oldId).readAllMap();
+        getMap(newId).putAll(oldMap);
+        session.setId(newId, false);
+        session.tellChangedSessionId(newId, oldId, notifySessionListeners, notifyContainerListeners);
```
Comment (mrniko) [inline redisson-tomcat/redisson-tomcat-10/src/main/java/org/redisson/tomcat/RedissonSessionManager.java:428]: please replace it with `super.changeSessionId(session, newId, true, true);`

File: redisson-tomcat/redisson-tomcat-7/src/main/java/org/redisson/tomcat/RedissonSessionManager.java [hunk 2]
```diff
@@ -417,5 +417,15 @@ public void store(HttpSession session) throws IOException {
...
         }
     }
-    
+ 
+    @Override
+    public void changeSessionId(Session session, String newId) {
+        String oldId = session.getIdInternal();
+        Map<String, Object> oldMap = getMap(oldId).readAllMap();
+        getMap(newId).putAll(oldMap);
+        session.setId(newId, false);
```
Comment (mrniko) [inline redisson-tomcat/redisson-tomcat-7/src/main/java/org/redisson/tomcat/RedissonSessionManager.java:426]: please replace it with `super.changeSessionId(session, newId, true, true);`

File: redisson-tomcat/redisson-tomcat-8/src/main/java/org/redisson/tomcat/RedissonSessionManager.java [hunk 3]
```diff
@@ -417,5 +417,15 @@ public void store(HttpSession session) throws IOException {
...
     }
-    
+
+    @Override
+    protected void changeSessionId(Session session, String newId, boolean notifySessionListeners,
+            boolean notifyContainerListeners) {
+        String oldId = session.getIdInternal();
+        Map<String, Object> oldMap = getMap(oldId).readAllMap();
+        getMap(newId).putAll(oldMap);
+        session.setId(newId, false);
```
Comment (mrniko) [inline redisson-tomcat/redisson-tomcat-8/src/main/java/org/redisson/tomcat/RedissonSessionManager.java:427]: please replace it with super.changeSessionId(session, newId, true, true);

File: redisson-tomcat/redisson-tomcat-9/src/main/java/org/redisson/tomcat/RedissonSessionManager.java [hunk 4]
```diff
@@ -417,5 +417,15 @@ public void store(HttpSession session) throws IOException {
...
     }
-    
+
+    @Override
+    protected void changeSessionId(Session session, String newId, boolean notifySessionListeners,
+            boolean notifyContainerListeners) {
+        String oldId = session.getIdInternal();
+        Map<String, Object> oldMap = getMap(oldId).readAllMap();
+        getMap(newId).putAll(oldMap);
+        session.setId(newId, false);
```
Comment (mrniko) [inline redisson-tomcat/redisson-tomcat-9/src/main/java/org/redisson/tomcat/RedissonSessionManager.java:427]: please replace it with super.changeSessionId(session, newId, true, true);

**Review by mrniko — CHANGES_REQUESTED** [review]

File: redisson-tomcat/redisson-tomcat-10/src/main/java/org/redisson/tomcat/RedissonSessionManager.java [hunk 5]
```diff
@@ -417,5 +417,15 @@ public void store(HttpSession session) throws IOException {
             sess.save();
         }
     }
-    
+
+    @Override
+    protected void changeSessionId(Session session, String newId, boolean notifySessionListeners,
+            boolean notifyContainerListeners) {
+        String oldId = session.getIdInternal();
+        Map<String, Object> oldMap = getMap(oldId).readAllMap();
```
Comment (mrniko) [inline redisson-tomcat/redisson-tomcat-10/src/main/java/org/redisson/tomcat/RedissonSessionManager.java:425]: use getMap(oldId).rename() instead

File: redisson-tomcat/redisson-tomcat-7/src/main/java/org/redisson/tomcat/RedissonSessionManager.java [hunk 6]
```diff
@@ -417,5 +417,15 @@ public void store(HttpSession session) throws IOException {
             sess.save();
         }
     }
-    
+ 
+    @Override
+    public void changeSessionId(Session session, String newId) {
+        String oldId = session.getIdInternal();
+        Map<String, Object> oldMap = getMap(oldId).readAllMap();
```
Comment (mrniko) [inline redisson-tomcat/redisson-tomcat-7/src/main/java/org/redisson/tomcat/RedissonSessionManager.java:424]: use getMap(oldId).rename() instead

File: redisson-tomcat/redisson-tomcat-8/src/main/java/org/redisson/tomcat/RedissonSessionManager.java [hunk 7]
```diff
@@ -417,5 +417,15 @@ public void store(HttpSession session) throws IOException {
             sess.save();
         }
     }
-    
+
+    @Override
+    protected void changeSessionId(Session session, String newId, boolean notifySessionListeners,
+            boolean notifyContainerListeners) {
+        String oldId = session.getIdInternal();
+        Map<String, Object> oldMap = getMap(oldId).readAllMap();
```
Comment (mrniko) [inline redisson-tomcat/redisson-tomcat-8/src/main/java/org/redisson/tomcat/RedissonSessionManager.java:425]: use getMap(oldId).rename() instead

File: redisson-tomcat/redisson-tomcat-9/src/main/java/org/redisson/tomcat/RedissonSessionManager.java [hunk 8]
```diff
@@ -417,5 +417,15 @@ public void store(HttpSession session) throws IOException {
             sess.save();
         }
     }
-    
+
+    @Override
+    protected void changeSessionId(Session session, String newId, boolean notifySessionListeners,
+            boolean notifyContainerListeners) {
+        String oldId = session.getIdInternal();
+        Map<String, Object> oldMap = getMap(oldId).readAllMap();
```
Comment (mrniko) [inline redisson-tomcat/redisson-tomcat-9/src/main/java/org/redisson/tomcat/RedissonSessionManager.java:425]: use getMap(oldId).rename() instead

File: redisson-tomcat/redisson-tomcat-9/src/main/java/org/redisson/tomcat/RedissonSession.java [hunk 9]
```diff
@@ -388,10 +388,8 @@ private void removeRedisAttribute(String name) {
     }
 
     public void save() {
-        if (map == null) {
```
Comment (mrniko) [inline redisson-tomcat/redisson-tomcat-9/src/main/java/org/redisson/tomcat/RedissonSession.java:391]: that's not needed if map was renamed

File: redisson-tomcat/redisson-tomcat-10/src/main/java/org/redisson/tomcat/RedissonSession.java [hunk 10]
```diff
@@ -393,10 +393,8 @@ private void removeRedisAttribute(String name) {
     }
 
     public void save() {
-        if (map == null) {
```
Comment (mrniko) [inline redisson-tomcat/redisson-tomcat-10/src/main/java/org/redisson/tomcat/RedissonSession.java:396]: that's not needed if the map was renamed

File: redisson-tomcat/redisson-tomcat-7/src/main/java/org/redisson/tomcat/RedissonSession.java [hunk 11]
```diff
@@ -411,10 +411,8 @@ private void removeRedisAttribute(String name) {
     }
 
     public void save() {
-        if (map == null) {
```
Comment (mrniko) [inline redisson-tomcat/redisson-tomcat-7/src/main/java/org/redisson/tomcat/RedissonSession.java:414]: that's not needed if the map was renamed

File: redisson-tomcat/redisson-tomcat-8/src/main/java/org/redisson/tomcat/RedissonSession.java [hunk 12]
```diff
@@ -388,10 +388,8 @@ private void removeRedisAttribute(String name) {
     }
 
     public void save() {
-        if (map == null) {
```
Comment (mrniko) [inline redisson-tomcat/redisson-tomcat-8/src/main/java/org/redisson/tomcat/RedissonSession.java:391]: that's not needed if the map was renamed

**Review by mrniko — CHANGES_REQUESTED** [review]

**Comment by bclay2116** [comment]
The above comments want to use a rename approach to update map to new key (which is admittedly superior). However, invoking rename at the changeSessionId level would result in same symptoms as original issue. This is because eventually setId gets invoked within StandardSession which would inform the Manager to delete and then resave the session. In the delete, the map gets deleted. I have new approach which overrides setId to do the rename.

**Comment by mrniko** [comment]
Thanks for contribution!
