### PR TITLE
Fix RLock trylock and unlock race condition

### LINKED ISSUE #6844: Attempt to unlock lock, not locked by current thread by node id in redisson 3.52
### Redis version

1.4.3

### Redisson version

3.52

### Redisson configuration

@bean("comSapRfmOdsLocksSpringRedissonClient")
RedissonClient redissonClient(Environment environment) {
String redisHost = environment.getProperty("redis-host");
Assert.notNull(redisHost, "Please specify a parameter redis-host");
String redisPort = environment.getProperty("redis-port");
Assert.notNull(redisPort, "Please specify a parameter redis-port");
String redisDatabase = environment.getProperty("redis-database");
Assert.notNull(redisDatabase, "Please specify a parameter redis-database");
String redisTls = environment.getProperty("redis-tls");

var redissonConfig = new Config();
String redisProtocol = Boolean.parseBoolean(redisTls) ? "rediss://" : "redis://";
var singleServerConfig = redissonConfig.useSingleServer()
    .setAddress(redisProtocol + redisHost + ":" + redisPort)
    .setDatabase(Integer.parseInt(redisDatabase));
String redisUsername = environment.getProperty("redis-username");
if (StringUtils.isNotEmpty(redisUsername)) {
  singleServerConfig.setUsername(redisUsername);
}
String redisPassword = environment.getProperty("redis-password");
if (StringUtils.isNotEmpty(redisPassword)) {
  singleServerConfig.setPassword(redisPassword);
}
redissonConfig.setLockWatchdogTimeout(30000); // 30 seconds
return Redisson.create(redissonConfig);
}

@bean("comSapRfmOdsLocksSpringLockEnvironment")
LockEnvironment lockEnvironment(@qualifier("OdsTenantProvider") Supplier tenantProvider,
RedissonClient redissonClient) {
return LockEnvironmentBuilder.create().lockTechnology(REDISSON).redissonClient(redissonClient)
.tenantProvider(tenantProvider)
.build();
}

### What is the Expected behavior?

No issues during processing with locks.

### What is the Actual behavior?

Hi, 
referring to issue https://github.com/redisson/redisson/issues/6651 we have upgraded our redisson version to 3.52.0. But still sporadically the "Attempt to unlock lock" issue is occurring. 

In most of the cases the issue occurs when we are processing large data packages. Processing large packages means the processing takes up to 1 minute. So the lock has to be valid during that time until the processing has finished. 
In our processing we have implemented also a resilient pattern. Interesting is that in case we get an "Attempt to unlock lock" our processing is trying to reprocess the package and directly gets a new lock! So that means even if we see the message "Attempt to unlock lock ..." your internal processing seams to release the lock correctly (maybe automatically).

Still the issue does not happen in redisson releases lower then 3.44. We are using method tryLock() of java.util.concurrent.locks to acquire a lock. In config the watchdogTimeOut is set to 30 seconds.

Thanks for your help.
Best Regards
Michael

### Additional information

"stacktrace": [
"java.lang.IllegalMonitorStateException: attempt to unlock lock, not locked by current thread by node id: b3ccb4a4-11ed-4997-8c1b-806fc81aa1c3 thread-id: 355705",
"\tat org.redisson.RedissonBaseLock.lambda$unlockAsync0$2(RedissonBaseLock.java:172)",
"\tat java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)",
"\tat java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source)",
"\tat java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)",
"\tat java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)",
"\tat org.redisson.command.RedisExecutor.handleSuccess(RedisExecutor.java:676)",
"\tat org.redisson.command.RedisExecutor.handleResult(RedisExecutor.java:652)",
"\tat org.redisson.command.RedisExecutor.checkAttemptPromise(RedisExecutor.java:629)",
"\tat org.redisson.command.RedisExecutor.lambda$execute$5(RedisExecutor.java:209)",
"\tat java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)",
"\tat java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)",
"\tat java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)",
"\tat java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)",
"\tat io.opentelemetry.javaagent.instrumentation.redisson.CompletableFutureWrapper.lambda$new$0(CompletableFutureWrapper.java:28)",
"\tat java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)",
"\tat java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)",
"\tat java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)",
"\tat java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)",
"\tat org.redisson.client.handler.CommandDecoder.completeResponse(CommandDecoder.java:535)",
"\tat org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:529)",
"\tat org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:449)",
"\tat org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:220)",
"\tat org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:148)",
"\tat org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:124)",
"\tat io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530)",
"\tat io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)",
"\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)",
"\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)",
"\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)",
"\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)",
"\tat io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1519)",
"\tat io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1377)",
"\tat io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1428)",
"\tat io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530)",
"\tat io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:469)",
"\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)",
"\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)",
"\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)",
"\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)",
"\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357)",
"\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)",
"\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)",
"\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868)",
"\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)",
"\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:796)",
"\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:732)",
"\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:658)",
"\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)",
"\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998)",
"\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)",
"\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)",
"\tat java.base/java.lang.Thread.run(Unknown Source)"
]
}

### PR DESCRIPTION
**Pull request by nhancdt2602**
Fix #6844

### CODE REVIEW

**Comment by mrniko** [comment]
Good catch!

File: redisson/src/test/java/org/redisson/RedissonLockTest.java [hunk 1]
```diff
@@ -497,6 +493,43 @@ public void run() {
...
+    @Test
+    public void testConcurrencyTryLockUnLock() throws InterruptedException {
+        Redisson client =  (Redisson) redisson;
+
+        AtomicBoolean emptyLockSet = new AtomicBoolean();
+
+        RLock instrumentedLock = new RedissonLock(client.getCommandExecutor(), "1testConcurrencyTryLockUnLock") {
+            @Override
+            public RFuture<Void> unlockAsync(long threadId) {
+                if (renewalScheduler.isLockSetEmpty()) {
```
Comment (mrniko) [inline redisson/src/test/java/org/redisson/RedissonLockTest.java]: use `Reflect.on(renewalScheduler)` instead

**Review by mrniko — CHANGES_REQUESTED** [review]

File: redisson/src/test/java/org/redisson/RedissonLockTest.java (hunk 1 above)
Comment (nhancdt2602) [reply redisson/src/test/java/org/redisson/RedissonLockTest.java]: I did switch to use `Reflect` and removed `isLockSetEmpty` helper method

**Comment by mrniko** [comment]
Thanks for contribution
