### PR TITLE
fix RTopicPattern resubscribe after failover

### LINKED ISSUE #6801: RPatternTopic does not resubscribe after failover
### Redis version

valkey 7.2

### Redisson version

3.52.0

### Redisson configuration

not sure what to put here, we're not using any fixed configuration, it's based on our app config; but we do set the following:
- `setLockWatchdogTimeout(10_000)`
- `setEventLoopGroup(new MultiThreadIoEventLoopGroup(new NamingThreadFactory("redisson"), NioIoHandler.newFactory()));`
- `setMasterName(...)`
- `setPassword(...)`
- and a few of `addSentinelAddress(...)`

(We tried with 2 sentinels and 1master+1slave and also with 3 sentinels, 1master+2slaves)

### What is the Expected behavior?

After a failover of the master to one of the slaves, `RPatternTopic` should re-subscribe to the pattern on the new master.

### What is the Actual behavior?

`RPatternTopic` does not resubscribe (even if the [documentation](https://redisson.pro/docs/data-and-services/publish-subscribe/#topic-pattern) says it will do it). We also stop receiving the messages from the `RPatternTopic`.
We also use a `RTopic` in our application; after a failover we see in the log that it does re-subscribe.

### Additional information

The `RPatternTopic` uses pattern `__keyspace@0__:forms.collab.*`. Valkey is configured with `notify-keyspace-events "g$xK"`

### PR DESCRIPTION
**Pull request by peterhalicky**
should fix #6801

### CODE REVIEW

**Comment by mrniko** [comment]
The test is always failing

**Comment by peterhalicky** [comment]
> The test is always failing

Can I have some more details? Where/how did it fail? How did you launch the test? Obviously I would not submit the PR if it wasn't working as expected at least on my environment.

**Comment by mrniko** [comment]
Below is the error:

```
org.awaitility.core.ConditionTimeoutException: Condition with Lambda expression in org.redisson.RedissonTopicPatternTest was not fulfilled within 1 minutes.

	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1160)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1129)
	at org.redisson.RedissonTopicPatternTest.lambda$testResubscribeInSentinel$20(RedissonTopicPatternTest.java:483)
	at org.redisson.RedisDockerTest.withSentinel(RedisDockerTest.java:290)
	at org.redisson.RedissonTopicPatternTest.testResubscribeInSentinel(RedissonTopicPatternTest.java:454)
Caused by: java.util.concurrent.TimeoutException
	at org.awaitility.core.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:101)
	at org.awaitility.core.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:81)
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:103)
	... 7 more
```

Code:

image

**Comment by peterhalicky** [comment]
Well, this looks more like a problem with sentinel and redisson's communication with it; nothing yet to do with my change. Any clues in the logs of either the test or redis/sentinel?

**Comment by mrniko** [comment]
Same test but for the cluster mode. Doesn't reproduce the issue. Can you adopt your test to the cluster mode?

```java
    @Test
    public void testReattachInCluster2() {
        SubscriptionMode subscriptionMode = SubscriptionMode.MASTER;
        withNewCluster((nds, instance) -> {
            Config config = instance.getConfig();
            config.useClusterServers()
                    .setSubscriptionMode(subscriptionMode);
            RedissonClient redisson = Redisson.create(config);

            RedisCluster nodes = redisson.getRedisNodes(RedisNodes.CLUSTER);
            for (RedisClusterSlave slave : nodes.getSlaves()) {
                slave.setConfig("notify-keyspace-events", "KgE$");
            }
            for (RedisClusterMaster master : nodes.getMasters()) {
                master.setConfig("notify-keyspace-events", "KgE$");
            }

            AtomicInteger executions = new AtomicInteger();

            RPatternTopic topic = redisson.getPatternTopic("__keyspace@0__:test.bucket.*", StringCodec.INSTANCE);
            topic.addListener(String.class, new PatternMessageListener<String>() {
                @Override
                public void onMessage(CharSequence pattern, CharSequence channel, String msg) {
                    executions.incrementAndGet();
                }
            });

            // ensure everything works before failover
            for (int i=0; i<10; i++) {
                redisson.getBucket(String.format("test.bucket.%d", i+1)).set("value");
            }

            List<ContainerState> masters = getMasterNodes(nds);
            stop(masters.get(0));

            try {
                Thread.sleep(40000);
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }

            nodes = redisson.getRedisNodes(RedisNodes.CLUSTER);
            for (RedisClusterSlave slave : nodes.getSlaves()) {
                slave.setConfig("notify-keyspace-events", "KgE$");
            }
            for (RedisClusterMaster master : nodes.getMasters()) {
                master.setConfig("notify-keyspace-events", "KgE$");
            }

            for (int i=0; i<10; i++) {
                redisson.getBucket(String.format("test.bucket.%d", i+1)).set("value");
            }

            await().atMost(5, TimeUnit.SECONDS).until(() -> executions.get() == 20);

            redisson.shutdown();
        });
    }
```

**Comment by peterhalicky** [comment]
I'll give it a try, although I'm a bit worried that in this case even the resubscribe might work (even without my patch). But yes, will try.

**Comment by peterhalicky** [comment]
As I suspected, in cluster mode resubscribe seems to work fine (I tried your test), so the problem is probably specific to sentinel mode.

That might mean that the fix I proposed isn't the right one, as the code where I made the change isn't specific to sentinel. If that's so I'm quite clueless as to where else to fix it.

File: redisson/src/test/java/org/redisson/RedissonTopicPatternTest.java [hunk 1]
```diff
@@ -450,5 +452,57 @@ public void onMessage(CharSequence pattern, CharSequence channel, Integer msg) {
...
+            config.useSentinelServers()
+                    .setRetryAttempts(8)
+                    .setSubscriptionsPerConnection(20)
+                    .setSubscriptionConnectionPoolSize(200);
+
+            RedissonClient redisson = Redisson.create(config);
+
+            RedisSentinelMasterSlave runningNodes = redisson.getRedisNodes(RedisNodes.SENTINEL_MASTER_SLAVE);
+            for (RedisSlave slave : runningNodes.getSlaves()) {
+                slave.setConfig("notify-keyspace-events", "KgE$");
```
Comment (seakider) [inline redisson/src/test/java/org/redisson/RedissonTopicPatternTest.java]:
```suggestion
                RedisNode node= (RedisNode) slave;
                RedisConnection conn = node.getClient().connect();
                conn.sync(RedisCommands.CONFIG_SET,"notify-keyspace-events", "KgE$");
```
`#RedisNode.setconfig()` is still using the master's connection，You may need to set the config using this way.

File: redisson/src/main/java/org/redisson/pubsub/PublishSubscribeService.java [hunk 2]
```diff
@@ -1007,13 +1007,13 @@ private void psubscribe(MasterSlaveEntry oldEntry, ChannelName channelName, Coll
         if (isMultiEntity(channelName)) {
             entry = connectionManager.getEntrySet()
                     .stream()
-                    .filter(e -> !name2PubSubConnection.containsKey(new PubSubKey(channelName, e)) && e != oldEntry)
+                    .filter(e -> !name2PubSubConnection.containsKey(new PubSubKey(channelName, e)))
```
Comment (seakider) [inline redisson/src/main/java/org/redisson/pubsub/PublishSubscribeService.java]:
```suggestion
                    .filter(e -> !name2PubSubConnection.containsKey(new PubSubKey(channelName, e))
                                && (!connectionManager.getServiceManager().getCfg().isClusterConfig() || e != oldEntry))
```
changed for sentinel mode only.

**Comment by mrniko** [comment]
@peterhalicky

any feedback regarding @seakider comments?

**Comment by peterhalicky** [comment]
I haven't had time to look at it yet. TBH I've worked around the issue in our code, but I will try to find some time.

File: redisson/src/test/java/org/redisson/RedissonTopicPatternTest.java (hunk 1 above)
Comment (peterhalicky) [reply redisson/src/test/java/org/redisson/RedissonTopicPatternTest.java]: Did you mean to cast the `slave` to something else? The cast is redundant and the code doesn't compile on L469, because `node` has no `getClient()`.

Comment (seakider) [reply redisson/src/test/java/org/redisson/RedissonTopicPatternTest.java]: Cast to [org.redisson.redisnode.RedisNode](https://github.com/redisson/redisson/blob/dd97de26a03bcc018f42556bf3ca5857b45dd313/redisson/src/main/java/org/redisson/redisnode/RedisNode.java#L61) , not `org.redisson.api.redisnode.RedisNode`.

**Comment by peterhalicky** [comment]
@mrniko suggestions from @seakider are added to the PR now

File: redisson/src/test/java/org/redisson/RedissonTopicPatternTest.java (hunk 1 above)
Comment (peterhalicky) [reply redisson/src/test/java/org/redisson/RedissonTopicPatternTest.java]: Thanks; there is an import `org.redisson.api.redisnode.*`, so I used an inline cast instead.

**Comment by mrniko** [comment]
@seakider 

Can we merged it?

**Comment by peterhalicky** [comment]
@mrniko do the tests pass? I couldn't get all tests to pass on my environment even without these changes, so I can't really tell if this broke something somewhere or not.

**Comment by seakider** [comment]
@mrniko 
The newly added test cases I attempted passed successfully, though I did not run the other test cases. Should you run these test cases and find them pass as well, I believe we can proceed with the merge operation.

**Comment by mrniko** [comment]
Thanks for contribution
